export type { Position } from "./interfaces/Position"
export type { Size } from "./interfaces/Size"
export { Color } from "./models/Color"
export { GameConfig } from "./GameConfig"
export { Game } from "./Game"
