export type { Position } from "./src/interfaces/Position"
export type { Size } from "./src/interfaces/Size"
export { Color } from "./src/models/Color"
export { GameConfig } from "./src/GameConfig"
export { Game } from "./src/Game"
